# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dani_d17/Documents/Software Security and Blockchain/Software-Food-Supply-Chain/GUI/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addressLabel = QtWidgets.QLabel(self.centralwidget)
        self.addressLabel.setObjectName("addressLabel")
        self.horizontalLayout.addWidget(self.addressLabel)
        self.addressInput = QtWidgets.QLineEdit(self.centralwidget)
        self.addressInput.setObjectName("addressInput")
        self.horizontalLayout.addWidget(self.addressInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.amountLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountLabel.setObjectName("amountLabel")
        self.horizontalLayout_2.addWidget(self.amountLabel)
        self.amountInput = QtWidgets.QLineEdit(self.centralwidget)
        self.amountInput.setObjectName("amountInput")
        self.horizontalLayout_2.addWidget(self.amountInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mintButton = QtWidgets.QPushButton(self.centralwidget)
        self.mintButton.setObjectName("mintButton")
        self.verticalLayout.addWidget(self.mintButton)
        self.burnButton = QtWidgets.QPushButton(self.centralwidget)
        self.burnButton.setObjectName("burnButton")
        self.verticalLayout.addWidget(self.burnButton)
        self.checkBalanceButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkBalanceButton.setObjectName("checkBalanceButton")
        self.verticalLayout.addWidget(self.checkBalanceButton)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.balanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.balanceLabel.setObjectName("balanceLabel")
        self.verticalLayout.addWidget(self.balanceLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recipientLabel = QtWidgets.QLabel(self.centralwidget)
        self.recipientLabel.setObjectName("recipientLabel")
        self.horizontalLayout_3.addWidget(self.recipientLabel)
        self.recipientInput = QtWidgets.QLineEdit(self.centralwidget)
        self.recipientInput.setObjectName("recipientInput")
        self.horizontalLayout_3.addWidget(self.recipientInput)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.transferButton = QtWidgets.QPushButton(self.centralwidget)
        self.transferButton.setObjectName("transferButton")
        self.verticalLayout.addWidget(self.transferButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addressLabel.setText(_translate("MainWindow", "Address Input"))
        self.amountLabel.setText(_translate("MainWindow", "Amount Input"))
        self.mintButton.setText(_translate("MainWindow", "Button Minting"))
        self.burnButton.setText(_translate("MainWindow", "Button Burn"))
        self.checkBalanceButton.setText(_translate("MainWindow", "Button Balance"))
        self.statusLabel.setText(_translate("MainWindow", "status"))
        self.balanceLabel.setText(_translate("MainWindow", "balance"))
        self.recipientLabel.setText(_translate("MainWindow", "Recipient Input"))
        self.transferButton.setText(_translate("MainWindow", "Button Transfer"))
