# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dani_d17/Documents/Software Security and Blockchain/Software-Food-Supply-Chain/GUI/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addressInput = QtWidgets.QLineEdit(self.centralwidget)
        self.addressInput.setObjectName("addressInput")
        self.verticalLayout.addWidget(self.addressInput)
        self.amountInput = QtWidgets.QLineEdit(self.centralwidget)
        self.amountInput.setObjectName("amountInput")
        self.verticalLayout.addWidget(self.amountInput)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        self.mintButton = QtWidgets.QPushButton(self.centralwidget)
        self.mintButton.setObjectName("mintButton")
        self.verticalLayout.addWidget(self.mintButton)
        self.checkBalanceButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkBalanceButton.setObjectName("checkBalanceButton")
        self.verticalLayout.addWidget(self.checkBalanceButton)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.balanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.balanceLabel.setObjectName("balanceLabel")
        self.verticalLayout.addWidget(self.balanceLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Button Connect"))
        self.mintButton.setText(_translate("MainWindow", "Button Minting"))
        self.checkBalanceButton.setText(_translate("MainWindow", "Button Balance"))
        self.statusLabel.setText(_translate("MainWindow", "status"))
        self.balanceLabel.setText(_translate("MainWindow", "balance"))
